const SERVER_ERROR = 500;
const NOT_FOUND = 404;
const BAD_REQUEST = 400;
const AUTH_ERROR = 401;
const CONFLICTING_REQUEST = 409;
const FORBIDDEN_ERROR = 403;

module.exports = {
  SERVER_ERROR,
  NOT_FOUND,
  BAD_REQUEST,
  AUTH_ERROR,
  CONFLICTING_REQUEST,
  FORBIDDEN_ERROR,
};
